---
title: "Syllabus"
subtitle: "Stat 151A: Linear Models"
toc: true
doi: "Spring 2024"
doi-title: Term
author:
    - Ryan Giordano
    - Dohyeong Ki
author-title: Instructors
abstract-title: ""
theme: [sandstone, assets/styles.scss]
toc-depth: 4
sidebar: false
---

::: {.callout-warning}
These course policies are a work in progress and subject to change.
:::

### Objectives

Linear models strike a remarkable balance between simplicity
and complexity: simple enough to permit detailed theoretical analysis,
but complex enough to exhibit many of the strengths and weaknesses
of statistics and machine learning more generally.  In this course, we
will explore classical and cutting-edge topics in statistics and
machine learning through the lens of linear models.  A strong
emphasis will be placed on mathematical rigor, real-world decision-making, 
and the interplay between the two.

#### Course goals

By the end of the course, you should be able to

- Express standard regression analyses both mathematically and in R code
- Critically relate the intended use of a regression analysis to its methods and assumptions
- Identify common practical and conceptual pitfalls of regression analysis, and to improve the analysis when possible
 - Communicate the process and results of a regression analysis simply and clearly for a broad audience, using well-organized prose, reproducible code, and effective data visualizations.    

### Prerequisites

This course will assume familiarity with the material in STAT 135 or STAT 102. 
STAT 135 implies other prerequisite courses (STAT 134 and
its prerequisites). In particular, you must have had linear algebra, so you
should be familiar with basic matrix operations, vector subspaces and
projections, rank and invertibility of matrices, and quadratic forms.

This semester of Stat151A will include labs and projects in the R language.
Proficiency with R at the level of the
\href{https://github.com/dlab-berkeley/R-Fundamentals}{D-lab fundamentals
course} is a prerequisite.  Students with a strong background in another
programming language (e.g. Python) will be permitted to enroll with the
understanding that they will learn R on their own prior to the start of the
class.  




### Materials

#### Textbook

The primary materials for the course are the lecture notes, which will be posted to the 
course website in advance of class. The following textbooks are useful supplementary texts 
but there is no need to purchase them:

- [Applied Regression Analysis and Generalized Linear Models](https://search.library.berkeley.edu/permalink/01UCS_BER/1thfj9n/alma991086117138306532), Fox
- [Statistics](https://wwnorton.com/books/9780393929720), Freedman, Pisani, and Purves
- [R for Data Science](https://r4ds.had.co.nz/), Wickham and Grolemund (freely available online)

#### RStudio

The software that we'll be using for our data analysis is the free and open-source language called R that we'll be interacting with via software called RStudio. As a Berkeley student, you have your own version of RStudio waiting you for at: [http://stat20.datahub.berkeley.edu](http://stat20.datahub.berkeley.edu). Most students taking Stat 20 have no experience programming; we'll teach you everything you need to know!

#### Course website

All of the assignments will be posted to the course website at [https://github.com/berkeley-stat151a/spring-2024](https://github.com/berkeley-stat151a/spring-2024). This also holds the course notes, the syllabus, and links to Gradescope, Ed, and RStudio.


### Assignments, Exams, and Grading

#### Grading.

Grades will not be curved except where otherwise noted.  Letter grades will be
assigned according the weighted points earned.  A score within [90-92%) will
earn an A-, [92-98%) will earn an A, and [99-100%) will earn an A+.  Scores in
the 80's will receive B's, in the 70's will receive C's, with the same
thresholds for plusses and minuses.  Scores below 70\% will be considered
failing.   Grades will be non-negotiable.

The weighting for the grades will be:
- Homework completion (each weighted equally): 16%
- Homework correctness (each weighted equally): 4%
- Quizzes (each weighted equally): 20%
- Final exam: 20%
- Group project: 20%
- Lab participation: 10%


#### Final exam.  
An in-person pencil-and-paper final exam will be
scheduled during the usual final exam week.

#### Quizzes.  
Every two weeks we will have an in-class quiz.  These
quizzes will take the place of a sitdown midterm exam (i.e., there will be
no midterm).

#### Homework.  
Homework assignments will be published on Fridays and due
two weeks later.  Homework will typically consist of a combination of
mathematical problems and data analysis in R.  All homework will be due as a pdf
via Gradescope unless otherwise noted.

The purpose of homework is for students to attempt to work through problems on
their own, both to advance their own understanding, and to allow the instructors
to monitor student learning.  Neither of these objectives are served if students
are copying answers.  For that reason, thoughtful and complete homework answers
will receive nearly full credit (80\% of the available homework points) even if
incorrect. We strongly encourage students to submit their own best efforts, even
if imperfect, rather than copy a correct answer.



#### Final project.
Students will form groups of up to three people to
submit a final project consisting of an analysis of a real dataset applying
principles and techniques from the course.

#### Turning-in assignments

You will be turning in your assignments on a platform called  [Gradescope](https://www.gradescope.com/). This is also the platform where your assignments will be graded, so you can return there to get feedback on your work. You are welcome to file a regrade request if you notice that we made an error in applying the rubric to your work, but be sure to do so **within a week** of the grades being posted. We will not accept regrade requests past that point.

In order to provide flexibility around emergencies that might arise for you throughout the semester (for example, missing a quiz due to COVID), we will apply for everyone:

-   one emergency drop for quizzes  
-   two emergency drops for homework 

This means that we will drop your lowest quiz score (which would be a 0 if you were absent) before computing your quiz average. For reading questions, we will drop your two lowest.

#### Late Work

Late work will not be accepted.  If work is not submitted on time, it will receive a zero.  
It is entirely the students' responsibility to turn work in on time.





### Policies

#### Course Culture

Students taking STAT151A come from a wide range of backgrounds. We hope to foster an inclusive and supportive learning environment based on curiosity rather than competition. All members of the course community—the instructor, students, tutors, and readers—are expected to treat each other with courtesy and respect. 

You will be interacting with course staff and fellow students in several different environments: in class, over the discussion forum, and in office hours. Some of these will be in person, some of them will be online, but the same expectations hold: be kind, be respectful, be professional.

If you are concerned about classroom environment issues created by other students or course staff, please come talk to the instructors
about it.


#### Collaboration policy

You are encouraged to collaborate with your fellow students on problem sets and labs, but the work you turn in should reflect your own understanding and all of your collaborators must be cited. The individual component of quizzes, reading questions, and exams must reflect only your work.

Researchers don't use one another's research without permission; scholars and students always use proper citations in papers; professors may not circulate or publish student papers without the writer's permission; and students may not circulate or post non-public materials (quizzes, exams, rubrics-any private class materials) from their class without the written permission of the instructor.

The general rule: you must not submit assignments that reflect the work of others unless they are a cited collaborator.

The following examples of collaboration **are** allowed and in fact encouraged!

- Discussing how to solve a problem with a classmate.
- Showing your code to a classmate along with an error message or confusing output.
- Posting snippets of your code to the discussion forum when seeking help.
- Helping other students solve questions on the discussion with conceptual pointers or snippets of code that doesn't whole hog give away the answer.
- Googling the text of an error message.
- Copying small snippets of code from answers on Stack Overflow.

The following examples are **not** allowed:

- Leaving a representation of your assignment (the text, a screenshot) where students (current and future) can access it. Examples of this include websites like course hero, on a group text chain, over discord/slack, or in a file passed on to future students.
- Accessing and submitting solutions to assignments from other students distributed as above. This includes copying written answers from other students and slightly modifying the language to differentiate it.
- Searching or using generative AI to produce complete problem solutions.
- Working on the final exam or individual quizzes in collaboration with other people or resources. These assignments must reflect individual work.
- Submitting work on an exam that reflects consultation with outside resources or other people. Exams must reflect individual work.

If you have questions about the boundaries of the policy, please ask. We’re always happy to clarify.

#### Violations of the collaboration policy

The integrity of our course depends on our ability to ensure that students do not violate the collaboration policy. We take this responsibility seriously and forward cases of academic misconduct to the Center for Student Conduct.

Students determined to have violated the academic misconduct policy by the Center for Student Conduct will receive a grade penalty in the course and a sanction from the university which is generally: (i) First violation: Non-Reportable Warning and educational intervention, (ii) Second violation: Suspension/Disciplinary Probation and educational interventions, (iii) Third violation: Dismissal.

And again, if you have questions about the boundaries of the collaboration policy, please ask!


#### Laptop policy

Laptops will not be permitted in lecture, but will be required for labs.
If you do not have access to a laptop, you can borrow
one from the University library.  See the
[UC Berkeley hardware lending program](https://studenttech.berkeley.edu/hardware-lending) for more details.  The
Student Technology Equity Program is another good resource.  Feel free to
contact the instructor if you have concerns about your access to needed
technology.

#### COVID policy

Maintaining your health and that of the Berkeley community is of primary importance to course staff, so if you are feeling ill or have been exposed to illness, please do not come to class. All of the materials used in class will be posted to the course website. You're encouraged to reach out to fellow students to discuss the class materials or stop by group tutoring or office hours to chat with a tutor or the instructor.

#### Accomodations for students with disabilities

Stat 20 is a course that is designed to allow all students to succeed. If you have letters of accommodations from the Disabled Students’ Program, please share them with your instructor as soon as possible, and we will work out the necessary arrangements.





::: {.callout-note}
These course polices are based on a template and text generously shared by Andrew Bray.  Thanks, Andrew!
:::
